/* ------------------------------------------------------------------
   LE CATALOGUE DES PROJETS - Sild'arcade production
   ------------------------------------------------------------------
   C'EST LE SEUL FICHIER A MODIFIER POUR AJOUTER UN PROJET.
   Les pages du site se remplissent toutes seules a partir d'ici.

   Un projet s'ecrit comme ceci :

     {
       titre:    "Le nom du jeu",
       machine:  "arcade",          arcade | nes | snes | n64 | gb | gamecube
                                    ps1 | ps2 | mastersystem | megadrive | soutiens
       etat:     "disponible",      disponible | encours | chantier | soutien
       genre:    "Traduction FR",   ce qu'on a fait dessus
       note:     "une phrase",      facultatif, s'affiche sous le titre
       image:    "assets/xxx.jpg",  facultatif ; sans image, une tuile
                                    dessinee avec le titre est generee
       lien:     "https://..."      le telechargement ; laisse vide tant
                                    que ce n'est pas sorti
     },

   LES ETATS
     disponible  le patch est telechargeable, le bouton s'allume
     encours     le travail avance, le bouton dit « en cours »
     chantier    c'est ouvert mais loin d'etre fini
     soutien     reserve aux soutiens : le bouton mene a Ko-fi (lien = la
                 page Ko-fi du jeu), jamais au fichier lui-meme

   Pour SORTIR un projet : passe son etat a "disponible" et colle son
   lien. Rien d'autre a toucher, nulle part.
------------------------------------------------------------------ */

const PROJETS = [

  /* ============================ ARCADE ============================ */
  { titre: "Luigi's Mansion Arcade", machine: "arcade", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_luigi_mansion_arcade.jpg",
    lien: "https://drive.google.com/file/d/1vpGscA6F780YEbTK5u1SInaoP2TuNy0x/view?usp=drive_link" },

  { titre: "Silent Hill Arcade", machine: "arcade", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_silent_hill_arcade.png",
    lien: "https://drive.google.com/file/d/1tJwgw3EDVunw41ECYNUqAeRVmEK_Dicd/view?usp=sharing" },

  { titre: "Jurassic Park", machine: "arcade", etat: "disponible",
    genre: "Doublage FR", image: "assets/banner_jurassic_park.png",
    note: "Raw Thrills", lien: "https://drive.google.com/file/d/1-s74KtXZZRvkDG0T8feRdEjRs2CMXKl2/view?usp=sharing" },

  { titre: "Rambo", machine: "arcade", etat: "encours",
    genre: "Traduction FR et doublage", image: "assets/banner_rambo.png",
    note: "Sega", lien: "" },

  { titre: "Knights of the Round", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1991", lien: "" },
  { titre: "The King of Dragons", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1991", lien: "" },
  { titre: "Cadillacs and Dinosaurs", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1993", lien: "" },
  { titre: "Dungeons & Dragons — Shadow over Mystara", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1996", lien: "" },
  { titre: "Battle Circuit", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1997", lien: "" },
  { titre: "Alien vs Predator", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1994", lien: "" },
  { titre: "Red Earth", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1996", lien: "" },
  { titre: "Black Tiger", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Capcom 1987", lien: "" },
  { titre: "Light Bringer / Dungeon Magic", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Taito", lien: "" },
  { titre: "Warrior Blade — Rastan Saga Episode III", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Taito 1991", lien: "" },
  { titre: "Chaos Breaker", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Taito", lien: "" },
  { titre: "Metamorphic Force", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Konami 1993", lien: "" },
  { titre: "Gaiapolis", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Konami 1993", lien: "" },
  { titre: "Crossed Swords", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "ADK 1991", lien: "" },
  { titre: "Sengoku 3", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "SNK 2001", lien: "" },
  { titre: "Shadow Force", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Technos 1993", lien: "" },
  { titre: "Wizard Fire / Dark Seal II", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Data East 1992", lien: "" },
  { titre: "Hook", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Irem 1992", lien: "" },
  { titre: "Rygar", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "Tecmo 1986", lien: "" },
  { titre: "The Gladiator / Shen Jian", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "IGS 2003", lien: "" },
  { titre: "Knights of Valour Super Heroes Plus", machine: "arcade", etat: "chantier",
    genre: "Traduction FR", note: "IGS", lien: "" },
  { titre: "Nosferatu Lilinor", machine: "arcade", etat: "chantier",
    genre: "Correctif", note: "Sega", lien: "" },

  /* ========================= NES / FAMICOM ======================== */
  { titre: "Retour vers le futur II et III", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_bttf.jpg",
    lien: "https://drive.google.com/file/d/1KXsiX2ZO_GVn60hHO1KMHkfbv2R16in1/view?usp=sharing" },
  { titre: "Indiana Jones et la dernière croisade", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    note: "toute l'histoire, en minuscules et accentuée",
    image: "assets/banner_nes_croisade.jpg",
    lien: "https://drive.google.com/file/d/1yPQXHLnmpnaPsIIl1zehQ_9oZZx2axLc/view?usp=sharing" },
  { titre: "Indiana Jones et le Temple maudit", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_temple.jpg",
    lien: "https://drive.google.com/file/d/18WAPXKwOuBc7G9ncWq9ez2J1qWcBXsfb/view?usp=sharing" },
  { titre: "Mad Max", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_madmax.jpg",
    lien: "https://drive.google.com/file/d/1ULd-YOv4esw-2oOhUi4EzjNM74XyBw_V/view?usp=sharing" },
  { titre: "Octobre rouge", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_octobre.jpg",
    lien: "https://drive.google.com/file/d/1NuVV0KhbGGTZCHmIVlQvMORmbpF89Eqa/view?usp=sharing" },
  { titre: "Platoon", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_platoon.jpg",
    lien: "https://drive.google.com/file/d/1y6QDk_tSecy4AAvXsRy2RfACNh88rRMk/view?usp=sharing" },
  { titre: "Wayne's World", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    image: "assets/banner_nes_wayne.jpg",
    lien: "https://drive.google.com/file/d/1SYb4wj1LoMxKlDBGsI4AmFFRQavfnjf8/view?usp=sharing" },
  { titre: "Le Surfer d'argent", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    note: "Marvel",
    image: "assets/banner_nes_surfer.jpg",
    lien: "https://drive.google.com/file/d/1U0DQfT1T7U0ALqRx8CLvjwoq-T587Y1q/view?usp=sharing" },
  { titre: "Superman", machine: "nes", etat: "disponible",
    genre: "Traduction FR",
    note: "Kemco",
    image: "assets/banner_nes_superman.jpg",
    lien: "https://drive.google.com/file/d/1C9zpZAtGTTzxaCN_6kj7Gz5sovTKlhk5/view?usp=sharing" },

  { titre: "Les Chevaliers du Zodiaque — La Légende d'Or", machine: "nes", etat: "encours",
    genre: "Traduction FR", image: "assets/banner_nes_zodiaque.jpg",
    lien: "" },
  { titre: "Dragon Ball - Le Secret du Dragon", machine: "nes", etat: "encours",
    genre: "Retraduction depuis le japonais", image: "assets/banner_nes_dragonball.jpg",
    lien: "" },
  { titre: "Cliffhanger", machine: "nes", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_nes_cliffhanger.jpg",
    lien: "https://drive.google.com/file/d/1h2NFFRd_8_O5FveZBJgbizEyGYRuZgQv/view?usp=sharing" },
  { titre: "Last Action Hero", machine: "nes", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_nes_last_action_hero.jpg",
    lien: "https://drive.google.com/file/d/19ptS9NQdqvcpPprUlTL0LQCnKucaN-0a/view?usp=sharing" },
  { titre: "Qui veut la peau de Roger Rabbit", machine: "nes", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_nes_roger_rabbit.jpg",
    lien: "https://drive.google.com/file/d/1lliiMOI0jURFyGfzew8lRLIJnZY-k5XK/view?usp=sharing" },
  { titre: "Le Punisher", machine: "nes", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_nes_punisher.jpg",
    lien: "https://drive.google.com/file/d/1Il6-LsnN6F37KeXEfUNp9HeJe6tHdaP5/view?usp=sharing" },
  { titre: "Mitsume ga Tooru — L'Enfant aux trois yeux", machine: "nes", etat: "chantier",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_nes_mitsume.jpg",
    lien: "" },
  { titre: "Samouraï Pizza Cats", machine: "nes", etat: "chantier",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_nes_pizza_cats.jpg",
    lien: "" },
  { titre: "Edgar de la Cambriole — L'Héritage de Pandore", machine: "nes", etat: "chantier",
    genre: "Traduction FR", image: "assets/banner_nes_edgar.jpg",
    lien: "" },
  { titre: "Shadowgate", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", image: "assets/banner_nes_shadowgate.jpg",
    lien: "https://drive.google.com/file/d/1G-RMNk1ia4gyl-Hw9GJb681zW0RzPBmt/view?usp=sharing" },

  /* ---- La collection Reset 60 (patchs du dossier Patch NES) ---- */
  { titre: "A Boy and His Blob", machine: "nes", etat: "disponible",
    genre: "VF Terminus Traduction passée en 60 Hz", note: "Absolute Entertainment 1989", image: "assets/banner_nes_a_boy_and_his_blob.jpg",
    lien: "https://drive.google.com/file/d/1RJxKrYCvvRX_LjiyJmA1GxhEYLuIJ3gL/view?usp=sharing" },
  { titre: "The Addams Family", machine: "nes", etat: "disponible",
    genre: "VF corrigée et conversion 60 Hz", note: "Ocean 1992", image: "assets/banner_nes_the_addams_family.jpg",
    lien: "https://drive.google.com/file/d/1MbwXlw_cavCOgYjuCesdRU2zbi68fYXY/view?usp=sharing" },
  { titre: "Adventures in the Magic Kingdom", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Capcom 1990", image: "assets/banner_nes_adventures_in_the_magic_kingdom.jpg",
    lien: "https://drive.google.com/file/d/1USQVoU1YY4p3yj5g2Fb6TghH-gNes56B/view?usp=sharing" },
  { titre: "Airwolf", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim", image: "assets/banner_nes_airwolf.jpg",
    lien: "https://drive.google.com/file/d/1wVvJg6DpZtTZiXzDQj7Sl_6sl_rQTWRu/view?usp=sharing" },
  { titre: "Al Unser Jr.'s Turbo Racing", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Data East 1990", image: "assets/banner_nes_al_unser_jr_s_turbo_racing.jpg",
    lien: "https://drive.google.com/file/d/1FlC2ab0mP2ru-SWq273rBLTtCVa6sIwV/view?usp=sharing" },
  { titre: "Aladdin", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Virgin 1994", image: "assets/banner_nes_aladdin.jpg",
    lien: "https://drive.google.com/file/d/1PISjUPtOXBYoKef7V4A5PhqMleXf5Ew5/view?usp=sharing" },
  { titre: "Alex DeMeo's Race America", machine: "nes", etat: "encours",
    genre: "Traduction FR", note: "Absolute Entertainment 1992", image: "assets/banner_nes_alex_demeo_s_race_america.jpg",
    lien: "https://drive.google.com/file/d/1bvhlqfZwzX9wUDMRjAwLkb6TvmyUkAUE/view?usp=sharing" },
  { titre: "Alien 3", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "LJN 1993", image: "assets/banner_nes_alien_3.jpg",
    lien: "https://drive.google.com/file/d/1PoGvkRqOeeUCCLXg4dYYKHSVPJRjXlFU/view?usp=sharing" },
  { titre: "Alpha Mission", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "SNK 1987", image: "assets/banner_nes_alpha_mission.jpg",
    lien: "https://drive.google.com/file/d/1SFeCnl1RIQyf_s0sb-k3_N1L2IEdSGmX/view?usp=sharing" },
  { titre: "Astérix", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Infogrames 1993", image: "assets/banner_nes_asterix.jpg",
    lien: "https://drive.google.com/file/d/1C5jN-6Xwbsmtr-ud8IReofQdxXkEccZz/view?usp=sharing" },
  { titre: "Banana Prince", machine: "nes", etat: "disponible",
    genre: "Traduction FR depuis le japonais", note: "Takara 1991", image: "assets/banner_nes_banana_prince.jpg",
    lien: "https://drive.google.com/file/d/1GXj9CnoAt7N0sLL8YVA4ySuUfGwbc9wR/view?usp=sharing" },
  { titre: "Barker Bill's Trick Shooting", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1989", image: "assets/banner_nes_barker_bill_s_trick_shooting.jpg",
    lien: "https://drive.google.com/file/d/19klWMPGnmtNNKDA2RK1Ksj93zE9NqsrE/view?usp=sharing" },
  { titre: "Baseball", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo", image: "assets/banner_nes_baseball.jpg",
    lien: "https://drive.google.com/file/d/1Czfr8dhQ0LVpJHQNjMuN3dAgjDTAg2ee/view?usp=sharing" },
  { titre: "Battleship", machine: "nes", etat: "disponible",
    genre: "VF corrigée et conversion 60 Hz", note: "Mindscape 1993", image: "assets/banner_nes_battleship.jpg",
    lien: "https://drive.google.com/file/d/1Za5y3Au-1AND9pDvi7jIaJdSwDbvmiIW/view?usp=sharing" },
  { titre: "Battletoads", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Rare", image: "assets/banner_nes_battletoads.jpg",
    lien: "https://drive.google.com/file/d/14F5MMhR-P4NTg3t0eBUOMt41GBME78VR/view?usp=sharing" },
  { titre: "La Belle et la Bête", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Hudson Soft 1994", image: "assets/banner_nes_la_belle_et_la_bete.jpg",
    lien: "https://drive.google.com/file/d/1cGckmOhNdd3F4WtYLPHeQWOH9PkC3ZmR/view?usp=sharing" },
  { titre: "Best of the Best: Championship Karate", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Electro Brain 1992", image: "assets/banner_nes_best_of_the_best_championship_karate.jpg",
    lien: "https://drive.google.com/file/d/1ZXjWxozlvKCoV9wkMJPeSFL2Mj_92Fyi/view?usp=sharing" },
  { titre: "Bigfoot", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1990", image: "assets/banner_nes_bigfoot.jpg",
    lien: "https://drive.google.com/file/d/1cScki30GG7XI9u4HIYC2wEgs_veqszc3/view?usp=sharing" },
  { titre: "Blaster Master", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Sunsoft 1988", image: "assets/banner_nes_blaster_master.jpg",
    lien: "https://drive.google.com/file/d/1UrLOa4PMwrPdCchwWgbAOVliw2QF802O/view?usp=sharing" },
  { titre: "Blue Shadow", machine: "nes", etat: "disponible",
    genre: "VF Terminus Traduction passée en 60 Hz", note: "Taito 1990", image: "assets/banner_nes_blue_shadow.jpg",
    lien: "https://drive.google.com/file/d/1BR6yHNJsOcOBAz1MDzjsU4kTyp_OV33_/view?usp=sharing" },
  { titre: "The Blues Brothers", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Titus 1991", image: "assets/banner_nes_the_blues_brothers.jpg",
    lien: "https://drive.google.com/file/d/12K7lGIeShTtWoS0RFe0F5EmwhvpoIFd8/view?usp=sharing" },
  { titre: "Bram Stoker's Dracula", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Sony Imagesoft 1993", image: "assets/banner_nes_bram_stoker_s_dracula.jpg",
    lien: "https://drive.google.com/file/d/1t8QZiret0qrcWx4HuRC-GNbM5OVLSkJ5/view?usp=sharing" },
  { titre: "California Games", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Milton Bradley 1989", image: "assets/banner_nes_california_games.jpg",
    lien: "https://drive.google.com/file/d/1gj09XxAaJe5tP5sbnCIdP0gC0go9h6aQ/view?usp=sharing" },
  { titre: "Championship Rally", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Kaken 1992", image: "assets/banner_nes_championship_rally.jpg",
    lien: "https://drive.google.com/file/d/1DEPMsOAlvcsMLg-QDJTpnr7iWuiq9hJW/view?usp=sharing" },
  { titre: "City Connection", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Jaleco", image: "assets/banner_nes_city_connection.jpg",
    lien: "https://drive.google.com/file/d/1ho4EvydiKtf078XS6naxVWYji1UgCQrH/view?usp=sharing" },
  { titre: "Clu Clu Land", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1984", image: "assets/banner_nes_clu_clu_land.jpg",
    lien: "https://drive.google.com/file/d/1nngcJLSqXW19mUXaK0q4Sz-Nz3hQbbtx/view?usp=sharing" },
  { titre: "Cobra Triangle", machine: "nes", etat: "encours",
    genre: "Traduction FR", note: "Rare / Nintendo 1989", image: "assets/banner_nes_cobra_triangle.jpg",
    lien: "https://drive.google.com/file/d/1lpNn8uKcFTQbzeTUk9kq8WvfX8LccJtH/view?usp=sharing" },
  { titre: "Cosmic Spacehead", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "Codemasters", image: "assets/banner_nes_cosmic_spacehead.jpg",
    lien: "https://drive.google.com/file/d/13M-oM31hn3Mlnr0hPaoHWDTSx5OjiN2i/view?usp=sharing" },
  { titre: "Crackout", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1991", image: "assets/banner_nes_crackout.jpg",
    lien: "https://drive.google.com/file/d/1fSTblqZIQayCbdHMxQ7WDOz6KuMp3_5P/view?usp=sharing" },
  { titre: "Danny Sullivan's Indy Heat", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Tradewest 1992", image: "assets/banner_nes_danny_sullivan_s_indy_heat.jpg",
    lien: "https://drive.google.com/file/d/1Jcwv7pCYQIxqOwh2ucBI72Zc2TSgwMpE/view?usp=sharing" },
  { titre: "Darkman", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ocean 1991", image: "assets/banner_nes_darkman.jpg",
    lien: "https://drive.google.com/file/d/102U2vww8LqTMjh7uEZpR9OPD0OD95q0f/view?usp=sharing" },
  { titre: "Days of Thunder", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Mindscape 1990", image: "assets/banner_nes_days_of_thunder.jpg",
    lien: "https://drive.google.com/file/d/1Kj5G7lMk_I8AydGqlgRAi8j_sdztox3R/view?usp=sharing" },
  { titre: "Defender of the Crown", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "Ultra Games (Konami) 1989", image: "assets/banner_nes_defender_of_the_crown.jpg",
    lien: "https://drive.google.com/file/d/1uHVzahslC3cHJONQH0nPqeyq5tEXsBUd/view?usp=sharing" },
  { titre: "Digger T. Rock", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Rare 1990", image: "assets/banner_nes_digger_t_rock.jpg",
    lien: "https://drive.google.com/file/d/1pdT3iQNdUMiZqWUXdboVM2hUsLJd2N97/view?usp=sharing" },
  { titre: "Donkey Kong Classics", machine: "nes", etat: "disponible",
    genre: "VF Génération IX et Brutapode89, menu traduit", note: "Nintendo 1988", image: "assets/banner_nes_donkey_kong_classics.jpg",
    lien: "https://drive.google.com/file/d/1Z3QPlQQ4ecylEUcqUk346zNOm7Vfe5cM/view?usp=sharing" },
  { titre: "Dropzone", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Mindscape 1992", image: "assets/banner_nes_dropzone.jpg",
    lien: "https://drive.google.com/file/d/1Luhwz1UJmKmpvt8Io0tOpXAZ9TTPM97a/view?usp=sharing" },
  { titre: "Lee Trevino's Fighting Golf", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "SNK 1988", image: "assets/banner_nes_lee_trevino_s_fighting_golf.jpg",
    lien: "https://drive.google.com/file/d/17K4WXuvsc-HbE67oJROt4PNpI4ThuHHT/view?usp=sharing" },
  { titre: "Eliminator Boat Duel", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Electro Brain 1991", image: "assets/banner_nes_eliminator_boat_duel.jpg",
    lien: "https://drive.google.com/file/d/1f9MCKoUfYzRdNuFcl_eMz_Y_2P4OEe2g/view?usp=sharing" },
  { titre: "Elite", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Imagineer 1991", image: "assets/banner_nes_elite.jpg",
    lien: "https://drive.google.com/file/d/1oxTuj3OO77oFCVjP0SkbBjrZmC_r3-gE/view?usp=sharing" },
  { titre: "F-15 Strike Eagle", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "MicroProse 1992", image: "assets/banner_nes_f_15_strike_eagle.jpg",
    lien: "https://drive.google.com/file/d/1eubSbWnXF30NtKLahOp7ndL3goCpQwbN/view?usp=sharing" },
  { titre: "Flight of the Intruder", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Mindscape 1991", image: "assets/banner_nes_flight_of_the_intruder.jpg",
    lien: "https://drive.google.com/file/d/1SFahS93TORf4DhGLtHaizs-JIdk20hg7/view?usp=sharing" },
  { titre: "The Flintstones: The Rescue of Dino & Hoppy", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Taito", image: "assets/banner_nes_the_flintstones_the_rescue_of_dino_hoppy.jpg",
    lien: "https://drive.google.com/file/d/1p4akzqi5mMVHiSqjebOZKfQqZzCKg2jz/view?usp=sharing" },
  { titre: "The Flintstones: The Surprise at Dinosaur Peak", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Taito", image: "assets/banner_nes_the_flintstones_the_surprise_at_dinosaur.jpg",
    lien: "https://drive.google.com/file/d/1vR-jVl5wuj6OOgcx8WDTQ69aY8EXFrWe/view?usp=sharing" },
  { titre: "Galaga", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Bandai 1988 (portage Namco de 1985)", image: "assets/banner_nes_galaga.jpg",
    lien: "https://drive.google.com/file/d/1eCkn8HGCOXNdB0iGYxahQvfKaPVLkKCg/view?usp=sharing" },
  { titre: "Galaxy 5000", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Activision 1990", image: "assets/banner_nes_galaxy_5000.jpg",
    lien: "https://drive.google.com/file/d/1TeV2xbmX-i_zAYaKivIE3AggTnTcJf5N/view?usp=sharing" },
  { titre: "Gauntlet II", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Mindscape 1990", image: "assets/banner_nes_gauntlet_ii.jpg",
    lien: "https://drive.google.com/file/d/1DtKdG-T8547Qpw4c75zHR5kLf-47M8D3/view?usp=sharing" },
  { titre: "George Foreman's KO Boxing", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1992", image: "assets/banner_nes_george_foreman_s_ko_boxing.jpg",
    lien: "https://drive.google.com/file/d/1z1PsFJhIpXeRCWGrzY46Jr7eMuZynyP9/view?usp=sharing" },
  { titre: "Godzilla", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Toho", image: "assets/banner_nes_godzilla.jpg",
    lien: "https://drive.google.com/file/d/11YUI21bzopXoODqNSu16DKZh12OQny0E/view?usp=sharing" },
  { titre: "Golf", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1984", image: "assets/banner_nes_golf.jpg",
    lien: "https://drive.google.com/file/d/1x8O7q8Y39mF4dXYsmakAEDe9mzGFQFPJ/view?usp=sharing" },
  { titre: "High Speed", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Tradewest 1991", image: "assets/banner_nes_high_speed.jpg",
    lien: "https://drive.google.com/file/d/1qL2xGbLaTYhgnhT3znarldQU_t6JADbb/view?usp=sharing" },
  { titre: "Home Alone 2", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "THQ", image: "assets/banner_nes_home_alone_2.jpg",
    lien: "https://drive.google.com/file/d/1p2LH15fHVqrucncEW-B0jjjvkZ7iCOOh/view?usp=sharing" },
  { titre: "Hudson Hawk", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Sony Imagesoft", image: "assets/banner_nes_hudson_hawk.jpg",
    lien: "https://drive.google.com/file/d/1H4FZuXA1NkNPNwb9EttYRO6EIv7I9kAv/view?usp=sharing" },
  { titre: "Iron Tank", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "SNK 1988", image: "assets/banner_nes_iron_tank.jpg",
    lien: "https://drive.google.com/file/d/1f0dp32tz3q-H_LazMvGECR8ReEm2n72s/view?usp=sharing" },
  { titre: "James Bond Jr", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "THQ 1992", image: "assets/banner_nes_james_bond_jr.jpg",
    lien: "https://drive.google.com/file/d/1ZAdTG8SVbB87QHQdCKVZWmY2Iq3lnsFP/view?usp=sharing" },
  { titre: "The Jetsons: Cogswell's Caper!", machine: "nes", etat: "disponible",
    genre: "VF Génération IX passée en 60 Hz", note: "Taito 1992", image: "assets/banner_nes_the_jetsons_cogswell_s_caper.jpg",
    lien: "https://drive.google.com/file/d/1OYe4jtLeCbVyVz3D0UFsN9PDknDKKGjN/view?usp=sharing" },
  { titre: "Jimmy Connors Tennis", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ubi Soft 1993", image: "assets/banner_nes_jimmy_connors_tennis.jpg",
    lien: "https://drive.google.com/file/d/1rGJebtLNeNiwTnB79VDo1smWZSpkdMMz/view?usp=sharing" },
  { titre: "Joe & Mac", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Data East 1991", image: "assets/banner_nes_joe_mac.jpg",
    lien: "https://drive.google.com/file/d/1-tcKful6JigUZm9BeuLYr05PPVudXnND/view?usp=sharing" },
  { titre: "Jurassic Park", machine: "nes", etat: "disponible",
    genre: "VF officielle Ocean passée en 60 Hz", note: "Ocean 1993", image: "assets/banner_nes_jurassic_park.jpg",
    lien: "https://drive.google.com/file/d/17N7tbe3f-6h8w3ftk3m7fd9vk-5c2fG5/view?usp=sharing" },
  { titre: "Kick Off", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Imagineer 1992", image: "assets/banner_nes_kick_off.jpg",
    lien: "https://drive.google.com/file/d/12SUD4vGq1493Yr7bvZf5knwOELTZtChw/view?usp=sharing" },
  { titre: "Konami Hyper Soccer", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1992", image: "assets/banner_nes_konami_hyper_soccer.jpg",
    lien: "https://drive.google.com/file/d/1Vfpwj7QzR6YvNA7OElaa87F6rkwnowBL/view?usp=sharing" },
  { titre: "Krusty's Fun House", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1992", image: "assets/banner_nes_krusty_s_fun_house.jpg",
    lien: "https://drive.google.com/file/d/17-LGsIpK-ufp76w7DapxQ5ginWhu8SV5/view?usp=sharing" },
  { titre: "The Legend of Prince Valiant", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Ocean 1992", image: "assets/banner_nes_the_legend_of_prince_valiant.jpg",
    lien: "https://drive.google.com/file/d/1yZgcHD1K484z_ICActVBNOAm8kh_RTE_/view?usp=sharing" },
  { titre: "Le Livre de la Jungle", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "Virgin Interactive 1994", image: "assets/banner_nes_le_livre_de_la_jungle.jpg",
    lien: "https://drive.google.com/file/d/1bzUzgXwwttXfMmRhDEJlxPollV351V8_/view?usp=sharing" },
  { titre: "Lunar Pool", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "FCI 1987", image: "assets/banner_nes_lunar_pool.jpg",
    lien: "https://drive.google.com/file/d/1UtYc9kb2T0OpfLl74ej95uU-CVshPWcB/view?usp=sharing" },
  { titre: "Mach Rider", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1985", image: "assets/banner_nes_mach_rider.jpg",
    lien: "https://drive.google.com/file/d/1kHpAHlFqMQ_iqtZyagDsx1k1NxxI8oCb/view?usp=sharing" },
  { titre: "Maniac Mansion", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Jaleco 1990", image: "assets/banner_nes_maniac_mansion.jpg",
    lien: "https://drive.google.com/file/d/1UoY9b4rXFf_9w304PLDzks-lA0W6hid5/view?usp=sharing" },
  { titre: "Marble Madness", machine: "nes", etat: "encours",
    genre: "Traduction FR", note: "Milton Bradley 1989", image: "assets/banner_nes_marble_madness.jpg",
    lien: "https://drive.google.com/file/d/1TcrlWBjk7bBpTAzZ81cYUzjXTsZT_7ph/view?usp=sharing" },
  { titre: "Mario & Yoshi", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo", image: "assets/banner_nes_mario_yoshi.jpg",
    lien: "https://drive.google.com/file/d/1t2WEnvf27G-RjiM4LwMnxRdhHhOcWKYQ/view?usp=sharing" },
  { titre: "McDonaldland", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "Virgin Games 1992", image: "assets/banner_nes_mcdonaldland.jpg",
    lien: "https://drive.google.com/file/d/13GuVQkUfL2cKCJPLqnKqo8izd6FdqKKA/view?usp=sharing" },
  { titre: "Mechanized Attack", machine: "nes", etat: "disponible",
    genre: "Traduction Génération IX, complétée", note: "SNK 1990", image: "assets/banner_nes_mechanized_attack.jpg",
    lien: "https://drive.google.com/file/d/1HmOKiQD9ewVrjcG5kqQ5BkZSRdMRv_r1/view?usp=sharing" },
  { titre: "The Miracle Piano Teaching System", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "The Software Toolworks 1990", image: "assets/banner_nes_the_miracle_piano_teaching_system.jpg",
    lien: "https://drive.google.com/file/d/1e-ZYKEVkDlhGjH4wIUVgAzFqfRUr3uVm/view?usp=sharing" },
  { titre: "Mission: Impossible", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ultra Games (Konami) 1990", image: "assets/banner_nes_mission_impossible.jpg",
    lien: "https://drive.google.com/file/d/1bAQcRL8XemS_I4-BZGSivI7MQ952AvnJ/view?usp=sharing" },
  { titre: "Lemmings", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Sunsoft", image: "assets/banner_nes_lemmings.jpg",
    lien: "https://drive.google.com/file/d/1i9RGtrYmJ8xon1KMxtLAKcRvE0ENaMtc/view?usp=sharing" },
  { titre: "Monopoly", machine: "nes", etat: "disponible",
    genre: "VF corrigée et conversion 60 Hz", image: "assets/banner_nes_monopoly.jpg",
    lien: "https://drive.google.com/file/d/1DxJF70I4enDqjMOeTjHOpdjzL1tAw0th/view?usp=sharing" },
  { titre: "Monster in My Pocket", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami", image: "assets/banner_nes_monster_in_my_pocket.jpg",
    lien: "https://drive.google.com/file/d/1b4Nf41RR-lQd5_fdLc1qVwJRStMnX1bW/view?usp=sharing" },
  { titre: "NES Open Tournament Golf", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1991", image: "assets/banner_nes_nes_open_tournament_golf.jpg",
    lien: "https://drive.google.com/file/d/1MY1hbbkaGztDH_-jhyNK0f5pdfTrDt9H/view?usp=sharing" },
  { titre: "New Ghostbusters II", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "HAL Laboratory", image: "assets/banner_nes_new_ghostbusters_ii.jpg",
    lien: "https://drive.google.com/file/d/13xzwnuNwAFQKhdcWqGHU0RkdH8lDbD-P/view?usp=sharing" },
  { titre: "Nigel Mansell's World Championship", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Gremlin 1992", image: "assets/banner_nes_nigel_mansell_s_world_championship.jpg",
    lien: "https://drive.google.com/file/d/1yld-zLO2uC9epl4zTqHQs0Dv1euhuwW8/view?usp=sharing" },
  { titre: "Noah's Ark", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1992", image: "assets/banner_nes_noah_s_ark.jpg",
    lien: "https://drive.google.com/file/d/1TxK_7Os7Zfth2qs-hSHGpz270k_Lu3EA/view?usp=sharing" },
  { titre: "Over Horizon", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Hot-B 1991", image: "assets/banner_nes_over_horizon.jpg",
    lien: "https://drive.google.com/file/d/1bmRBFmbtoZbhHINcXWxoDW1KR_91Q2Te/view?usp=sharing" },
  { titre: "Paperboy 2", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Mindscape 1992", image: "assets/banner_nes_paperboy_2.jpg",
    lien: "https://drive.google.com/file/d/1QDA5C-h90YXonpa38IUIwT5LBAUmeS7K/view?usp=sharing" },
  { titre: "Parasol Stars: Rainbow Islands II", machine: "nes", etat: "disponible",
    genre: "Région corrigée, VF Terminus Traduction (reste en 50 Hz)", note: "Ocean", image: "assets/banner_nes_parasol_stars_rainbow_islands_ii.jpg",
    lien: "https://drive.google.com/file/d/1QMpm8Uv0MOgivRACh2k7L9rhKx6jz8Ki/view?usp=sharing" },
  { titre: "Pinbot", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1990", image: "assets/banner_nes_pinbot.jpg",
    lien: "https://drive.google.com/file/d/1dENhD5UBlUhMmCAVoEgHH6dNJXWnLWhU/view?usp=sharing" },
  { titre: "Pirates!", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ultra Games 1991", image: "assets/banner_nes_pirates.jpg",
    lien: "https://drive.google.com/file/d/1pr-2CzaFPFs1nBDKciBXNbXvFA908UnH/view?usp=sharing" },
  { titre: "Prince of Persia", machine: "nes", etat: "disponible",
    genre: "Conversion 50 Hz vers 60 Hz", note: "Virgin Games 1992", image: "assets/banner_nes_prince_of_persia.jpg",
    lien: "https://drive.google.com/file/d/1dsgQUsTpdgTFzH8PJ0p6yPBxrWimSitK/view?usp=sharing" },
  { titre: "R.C. Pro-Am II", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Tradewest", image: "assets/banner_nes_r_c_pro_am_ii.jpg",
    lien: "https://drive.google.com/file/d/10mx8GkwAlxKu0Yu4kzIAZksOxyyVUhTq/view?usp=sharing" },
  { titre: "Rackets & Rivals", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1993", image: "assets/banner_nes_rackets_rivals.jpg",
    lien: "https://drive.google.com/file/d/1XxIiArafGvynfcZ4811z52gzQ0H5n5BA/view?usp=sharing" },
  { titre: "Rampart", machine: "nes", etat: "encours",
    genre: "Traduction FR et conversion 60 Hz", note: "Jaleco 1992", image: "assets/banner_nes_rampart.jpg",
    lien: "https://drive.google.com/file/d/1vYOOAXIdrsBcEaEVkH3YceR3qC-eVqGm/view?usp=sharing" },
  { titre: "Road Runner", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Tengen 1989", image: "assets/banner_nes_road_runner.jpg",
    lien: "https://drive.google.com/file/d/1PNhSAkfxnE85LQGAYT94qZMiU4O1pcZY/view?usp=sharing" },
  { titre: "Robin des Bois, prince des voleurs", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Virgin", image: "assets/banner_nes_robin_des_bois_prince_des_voleurs.jpg",
    lien: "https://drive.google.com/file/d/1tc0Jbm_9TYKqaTyYx8y7-cHNc_oGTUk9/view?usp=sharing" },
  { titre: "The Rocketeer", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Bandai 1991", image: "assets/banner_nes_the_rocketeer.jpg",
    lien: "https://drive.google.com/file/d/1YBAKxluI_ve0l0hTZf0V0PJ46dcfPalL/view?usp=sharing" },
  { titre: "Le Roi Lion", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Virgin 1995", image: "assets/banner_nes_le_roi_lion.jpg",
    lien: "https://drive.google.com/file/d/1UeY_fehS-mT7gIIt0xn-tGOhViFDxetn/view?usp=sharing" },
  { titre: "Les Schtroumpfs", machine: "nes", etat: "disponible",
    genre: "Région corrigée (reste en 50 Hz)", note: "Infogrames 1994", image: "assets/banner_nes_les_schtroumpfs.jpg",
    lien: "https://drive.google.com/file/d/1Z4Bcbvn3WD7oloxUlMheqQwAoFMExdva/view?usp=sharing" },
  { titre: "Section-Z", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Capcom 1987", image: "assets/banner_nes_section_z.jpg",
    lien: "https://drive.google.com/file/d/10KoTAcfhZVaXuKTuSRkWsGarjyBrThuY/view?usp=sharing" },
  { titre: "Silent Service", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "MicroProse", image: "assets/banner_nes_silent_service.jpg",
    lien: "https://drive.google.com/file/d/1bqQ7wpWe1az-SXmRa89md-oHLZT0PEQ4/view?usp=sharing" },
  { titre: "The Simpsons: Bart vs the World", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim", image: "assets/banner_nes_the_simpsons_bart_vs_the_world.jpg",
    lien: "https://drive.google.com/file/d/1qr0eRsUQSWtLm9NQV9E0sN1IsTPvMNVu/view?usp=sharing" },
  { titre: "The Simpsons: Bartman Meets Radioactive Man", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1992", image: "assets/banner_nes_the_simpsons_bartman_meets_radioactive_m.jpg",
    lien: "https://drive.google.com/file/d/1T-LbTsKP8SCk3eVQ89iNnHtkbbNTQUdx/view?usp=sharing" },
  { titre: "Smash T.V.", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1991", image: "assets/banner_nes_smash_t_v.jpg",
    lien: "https://drive.google.com/file/d/1oIqT1Zy5QiDpmvab2nNOriLE8nP8cFA4/view?usp=sharing" },
  { titre: "Snake Rattle 'n Roll", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1990", image: "assets/banner_nes_snake_rattle_n_roll.jpg",
    lien: "https://drive.google.com/file/d/1RF00cE_nHFsKBjWPc3gGUEyi0v5Go0oo/view?usp=sharing" },
  { titre: "Solar Jetman: Hunt for the Golden Warpship", machine: "nes", etat: "encours",
    genre: "Traduction FR", note: "Tradewest 1990", image: "assets/banner_nes_solar_jetman_hunt_for_the_golden_warpshi.jpg",
    lien: "https://drive.google.com/file/d/1zIRWnibCJ9kJMpAxtJEcU0kXtY1liFy2/view?usp=sharing" },
  { titre: "Space Harrier", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Takara 1989", image: "assets/banner_nes_space_harrier.jpg",
    lien: "https://drive.google.com/file/d/1nq_Qy0Ek3Lg4axVxTX7LZMV-mnqaQzHf/view?usp=sharing" },
  { titre: "Spider-Man: Return of the Sinister Six", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "LJN", image: "assets/banner_nes_spider_man_return_of_the_sinister_six.jpg",
    lien: "https://drive.google.com/file/d/106ihe2-sbf4Tcvgc4FcGDb_3KHAL87SK/view?usp=sharing" },
  { titre: "Spy vs Spy", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Kemco 1988", image: "assets/banner_nes_spy_vs_spy.jpg",
    lien: "https://drive.google.com/file/d/13ASHRjRQ1sgBd3Um-XkT7oT8fHlY-kAX/view?usp=sharing" },
  { titre: "Star Trek: 25th Anniversary", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ultra Games", image: "assets/banner_nes_star_trek_25th_anniversary.jpg",
    lien: "https://drive.google.com/file/d/1o5RGBayV0aTOfKr6nb1_MkYj1F1pSbxV/view?usp=sharing" },
  { titre: "Stealth ATF", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Activision 1989", image: "assets/banner_nes_stealth_atf.jpg",
    lien: "https://drive.google.com/file/d/1FmF1m5EHNuP1faV2d9anIicmR94QkpaL/view?usp=sharing" },
  { titre: "Super Turrican", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Rainbow Arts 1993", image: "assets/banner_nes_super_turrican.jpg",
    lien: "https://drive.google.com/file/d/15-fH5aOvP7Bs_zg4t945D34-xCOoHZP0/view?usp=sharing" },
  { titre: "Swamp Thing", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "THQ 1992", image: "assets/banner_nes_swamp_thing.jpg",
    lien: "https://drive.google.com/file/d/1_VxTnrMLs3IfCAOcxbNGxGZ2DGN1vGXO/view?usp=sharing" },
  { titre: "Sword Master", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Activision 1992", image: "assets/banner_nes_sword_master.jpg",
    lien: "https://drive.google.com/file/d/1ys8K78uOOr0glnuApCVs0nHamaqOP4uq/view?usp=sharing" },
  { titre: "Swords and Serpents", machine: "nes", etat: "disponible",
    genre: "VF corrigée et conversion 60 Hz", note: "Acclaim 1990", image: "assets/banner_nes_swords_and_serpents.jpg",
    lien: "https://drive.google.com/file/d/1ySMyz2dZu-tvULZ8c8_zztXg9m3uhSdp/view?usp=sharing" },
  { titre: "Tecmo World Cup Soccer", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Tecmo 1990", image: "assets/banner_nes_tecmo_world_cup_soccer.jpg",
    lien: "https://drive.google.com/file/d/14v9lzH55QAr0L_mRGVUSS-TnL1grg0j2/view?usp=sharing" },
  { titre: "Teenage Mutant Ninja Turtles: Tournament Fighters", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1993", image: "assets/banner_nes_teenage_mutant_ninja_turtles_tournament_.jpg",
    lien: "https://drive.google.com/file/d/1XKEfHEsTWh9OayhUGMRa4mNumkOtCj-R/view?usp=sharing" },
  { titre: "Lethal Weapon", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Ocean", image: "assets/banner_nes_lethal_weapon.jpg",
    lien: "https://drive.google.com/file/d/1A44Osn7aTaMGUhj2BlHV9iAThOMqdMzp/view?usp=sharing" },
  { titre: "Time Lord", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Milton Bradley", image: "assets/banner_nes_time_lord.jpg",
    lien: "https://drive.google.com/file/d/1XfUSMEl4c5BIXm4hsSmbA3h79N__vHDJ/view?usp=sharing" },
  { titre: "Tiny Toon Adventures: Cartoon Workshop", machine: "nes", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_nes_tiny_toon_adventures_cartoon_workshop.jpg",
    lien: "https://drive.google.com/file/d/1_CSW4a-Q9mLszQujWbLxPynM-kAM6efi/view?usp=sharing" },
  { titre: "To The Earth", machine: "nes", etat: "encours",
    genre: "Traduction FR", note: "Nintendo 1989", image: "assets/banner_nes_to_the_earth.jpg",
    lien: "https://drive.google.com/file/d/1k8A0wPTcY19JWrdsOXL7-Hv3yHeTtVUL/view?usp=sharing" },
  { titre: "Tom & Jerry", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Hi Tech Expressions 1991", image: "assets/banner_nes_tom_jerry.jpg",
    lien: "https://drive.google.com/file/d/1r3iR4C4toXorXgfMu_9wFI3n8Q0yIhqo/view?usp=sharing" },
  { titre: "Top Gun: The Second Mission", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami", image: "assets/banner_nes_top_gun_the_second_mission.jpg",
    lien: "https://drive.google.com/file/d/19X_ztek4z4HhW_UOubMse9m15dLmcCtH/view?usp=sharing" },
  { titre: "Top Players' Tennis", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Asmik 1990", image: "assets/banner_nes_top_players_tennis.jpg",
    lien: "https://drive.google.com/file/d/1Gk5x0hfbyvJlSoaC2V1b2GtiCQ6sty-e/view?usp=sharing" },
  { titre: "Total Recall", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1990", image: "assets/banner_nes_total_recall.jpg",
    lien: "https://drive.google.com/file/d/1kknkAkwdtr9icmFaBYxjX_9hkbuZPIPI/view?usp=sharing" },
  { titre: "Track & Field II", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Konami 1988", image: "assets/banner_nes_track_field_ii.jpg",
    lien: "https://drive.google.com/file/d/1X9wAjsCtz1PHCPIMxp78gOVIHnT7Z2IH/view?usp=sharing" },
  { titre: "Trog", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1991", image: "assets/banner_nes_trog.jpg",
    lien: "https://drive.google.com/file/d/1_UJqR2LZSAuH6GvNSHZYiQ7HRktwNYSh/view?usp=sharing" },
  { titre: "Ultimate Air Combat", machine: "nes", etat: "disponible",
    genre: "VF corrigée", note: "Activision 1992", image: "assets/banner_nes_ultimate_air_combat.jpg",
    lien: "https://drive.google.com/file/d/1MzGR4AQn8QvXM8kJEG4dD70BY5YGS-qU/view?usp=sharing" },
  { titre: "Wario's Woods", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo", image: "assets/banner_nes_wario_s_woods.jpg",
    lien: "https://drive.google.com/file/d/1wUcWqNxtEdvq1AFm4sj4LZkUJWR-KKzd/view?usp=sharing" },
  { titre: "Wizards & Warriors III - Kuros: Visions of Power", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Rare", image: "assets/banner_nes_wizards_warriors_iii_kuros_visions_of_po.jpg",
    lien: "https://drive.google.com/file/d/1ASLI14CDWKwsxtF1t3S4pHq4fwT1c-O5/view?usp=sharing" },
  { titre: "WWF King of the Ring", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "LJN 1993", image: "assets/banner_nes_wwf_king_of_the_ring.jpg",
    lien: "https://drive.google.com/file/d/1NnQpS0SA1_SOUKBvK2WWzieS7RHjhf2R/view?usp=sharing" },
  { titre: "WWF WrestleMania", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Acclaim 1989", image: "assets/banner_nes_wwf_wrestlemania.jpg",
    lien: "https://drive.google.com/file/d/1zwh5gWOLLuQy8gNJ5FLP9TfmkOIp0fGV/view?usp=sharing" },
  { titre: "Yoshi's Cookie", machine: "nes", etat: "disponible",
    genre: "Traduction FR", note: "Nintendo 1993", image: "assets/banner_nes_yoshi_s_cookie.jpg",
    lien: "https://drive.google.com/file/d/1Gz8xWIBbEILqy0dmbDM6CC4d9jk-6kbp/view?usp=sharing" },

  /* ======================= SUPER NINTENDO ========================= */
  /* (les projets Super Nintendo / Super Famicom se rangent ici,
      avec machine: "snes") */

  /* ====================== POUR LES SOUTIENS ======================= */
  /* Traductions reservees a ceux qui soutiennent sur Ko-fi. Le lien est
     celui de Ko-fi, JAMAIS celui du fichier : ce catalogue est public. */
  { titre: "Akira", machine: "soutiens", etat: "soutien",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_soutiens_akira.jpg",
    lien: "https://ko-fi.com/s/3d0d482cd2" },
  { titre: "Jetman", machine: "soutiens", etat: "soutien",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_soutiens_jetman.jpg",
    lien: "https://ko-fi.com/s/3d0d482cd2" },
  { titre: "L'Empereur", machine: "soutiens", etat: "soutien",
    genre: "Traduction FR", note: "Koei", image: "assets/banner_nes_empereur.jpg",
    lien: "https://ko-fi.com/s/3d0d482cd2" },
  { titre: "Sweet Home", machine: "soutiens", etat: "soutien",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_soutiens_sweet_home.jpg",
    lien: "https://ko-fi.com/s/3d0d482cd2" },
  { titre: "Ultraman Club 3", machine: "soutiens", etat: "soutien",
    genre: "Traduction FR depuis le japonais", image: "assets/banner_nes_ultraman.jpg",
    lien: "https://ko-fi.com/s/3d0d482cd2" },

  /* ============== AUTRES CONSOLES (gb, gamecube, ps1, ps2...) ============== */
  { titre: "Haunting Ground", machine: "ps2", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_haunting_ground.jpg",
    note: "PlayStation 2",
    lien: "https://drive.google.com/file/d/1cT3uTXQ7OOCK5Dex2r3xnNNTU_415mon/view?usp=sharing" },

  { titre: "Resident Evil Outbreak File #1 et #2", machine: "ps2", etat: "disponible",
    genre: "Traduction FR", image: "assets/banner_outbreak.jpg",
    note: "PlayStation 2",
    lien: "https://drive.google.com/file/d/1ngqfOuKsUAwxgQLAz_AA1oaISSJZbby9/view?usp=drive_link" },

  { titre: "Resident Evil Gaiden", machine: "gb", etat: "encours",
    genre: "Traduction FR", image: "assets/banner_gaiden.png",
    note: "Game Boy Color", lien: "" }
];
